apiVersion: v1
kind: Service
metadata:
  name: cortex-translate-service
  labels:
    app: cortex-translate-service
spec:
  selector:
    app: cortex-translate-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
