name: ClusterFuzzLite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: read-all

jobs:
  PR:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ matrix.sanitizer }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        sanitizer:
        - address
    steps:
    - name: Build Fuzzers
      id: build
      uses: google/clusterfuzzlite/actions/build_fuzzers@11d512a842bfae6f43698d28ed5554da0a200de6
      with:
        language: python
        sanitizer: ${{ matrix.sanitizer }}
    - name: Run Fuzzers
      uses: google/clusterfuzzlite/actions/run_fuzzers@11d512a842bfae6f43698d28ed5554da0a200de6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        fuzz-seconds: 600
        mode: 'code-change'
        sanitizer: ${{ matrix.sanitizer }}
